export type MediaKind = "image" | "video";

export interface MediaItem {
  id: string;
  file: File;
  kind: MediaKind;
  url: string;
  duration: number;
  /** Actual clip length in seconds, only known for videos once metadata loads. */
  sourceDuration: number | null;
}

export type TransitionType = "none" | "fade";

export interface VideoSettings {
  transition: TransitionType;
  transitionDuration: number;
  resolution: { width: number; height: number };
  fps: number;
  musicFile: File | null;
  /** Voiceover track generated by the narrated-script mode. Mixed on top of musicFile if both are set. */
  narrationFile: File | null;
}

/** A single caption reveal unit (roughly a "word") with its timing within the narration track. */
export interface CaptionWord {
  text: string;
  start: number;
  end: number;
}

export interface CaptionSentence {
  text: string;
  words: CaptionWord[];
  start: number;
  end: number;
}

export type NarrationTimingSource = "boundary" | "estimated";

export interface NarrationResult {
  /** null when generated in "no voiceover" mode — captions with no audio track. */
  audioFile: File | null;
  duration: number;
  sentences: CaptionSentence[];
  timingSource: NarrationTimingSource;
}
